class LessonData:
    """Class dùng để lưu trữ dữ liệu thô của bài học"""
    def __init__(self, title, grade, xp, lesson_id):
        self.title = title
        self.grade = grade
        self.xp = xp
        self.lesson_id = lesson_id
theory_data = {
    1: {
        # TẬP 1
        "Bài 1. Các số 0, 1, 2, 3, 4, 5": "Nhận biết số lượng các nhóm đồ vật và cách đọc, viết các chữ số từ 0 đến 5. Số 0 biểu thị không có vật nào.",
        "Bài 2. Các số 6, 7, 8, 9, 10": "Nhận biết và cách đọc, viết các số từ 6 đến 10. Số 10 là số có hai chữ số đầu tiên.",
        "Bài 3. Nhiều hơn, ít hơn, bằng nhau": "So sánh hai nhóm đồ vật bằng cách ghép đôi 1-1 để xác định nhóm nào thừa ra (nhiều hơn) hoặc thiếu (ít hơn).",
        "Bài 4. So sánh số": "Sử dụng các ký hiệu >, <, = để so sánh độ lớn giữa hai số trong phạm vi 10.",
        "Bài 5. Mấy và mấy": "Làm quen với cấu tạo số qua sơ đồ tách - gộp. Ví dụ: 5 gồm 4 và 1, hoặc 5 gồm 3 và 2.",
        "Bài 6. Luyện tập chung": "Củng cố kiến thức về đếm số và so sánh trong phạm vi 10.",
        "Bài 7. Hình vuông, hình tròn, hình tam giác, hình chữ nhật": "Nhận dạng các hình phẳng cơ bản thông qua hình dáng đặc trưng của chúng trong thực tế.",
        "Bài 8. Thực hành lắp ghép, xếp hình": "Sử dụng các hình phẳng đã học để tạo thành các hình mới sinh động.",
        "Bài 9. Luyện tập chung": "Ôn tập về các hình phẳng đã học.",
        "Bài 10. Phép cộng trong phạm vi 10": "Ý nghĩa của phép cộng là 'gộp lại'. Làm quen với dấu cộng (+) và dấu bằng (=).",
        "Bài 11. Phép trừ trong phạm vi 10": "Ý nghĩa của phép trừ là 'bớt đi'. Làm quen với dấu trừ (-) và các bài toán thực tế về bớt vật dụng.",
        "Bài 12. Bảng cộng, bảng trừ trong phạm vi 10": "Hệ thống hóa các phép tính cộng, trừ cơ bản để ghi nhớ nhanh.",
        "Bài 13. Luyện tập chung": "Thực hành tính toán cộng, trừ trong phạm vi 10.",
        "Bài 14. Khối lập phương, khối hộp chữ nhật": "Nhận biết các hình khối trong không gian qua các đồ vật như hộp quà, xúc xắc, viên gạch.",
        "Bài 15. Vị trí, định hướng trong không gian": "Xác định các phía: Trên - dưới, trước - sau, trái - phải và vị trí ở giữa.",
        "Bài 16. Luyện tập chung": "Củng cố kiến thức về hình khối và vị trí.",
        "Bài 17. Ôn tập các số trong phạm vi 10": "Ôn lại cách đọc, viết và thứ tự số.",
        "Bài 18. Ôn tập phép cộng, phép trừ trong phạm vi 10": "Ôn luyện kỹ năng tính toán học kỳ 1.",
        "Bài 19. Ôn tập hình học": "Ôn tập nhận biết hình phẳng và hình khối.",
        "Bài 20. Ôn tập chung": "Tổng kết kiến thức toán học kỳ 1 lớp 1.",
        
        # TẬP 2
        "Bài 21. Các số đến 20": "Đọc, viết các số từ 11 đến 20. Nhận biết cấu tạo gồm 1 chục và các đơn vị.",
        "Bài 22. Phép cộng (không nhớ) trong phạm vi 20": "Cộng các số bằng cách đếm thêm hoặc cộng hàng đơn vị với hàng đơn vị.",
        "Bài 23. Phép trừ (không nhớ) trong phạm vi 20": "Trừ các số bằng cách đếm lùi hoặc trừ hàng đơn vị cho hàng đơn vị.",
        "Bài 24. Luyện tập chung": "Thực hành tính toán trong phạm vi 20.",
        "Bài 25. Các số đến 100": "Nhận biết các số tròn chục và các số có hai chữ số đến 100.",
        "Bài 26. Đơn vị đo độ dài": "Làm quen với đơn vị xăng-ti-mét (cm) và cách dùng thước đo độ dài.",
        "Bài 27. Thực hành ước lượng và đo độ dài": "Sử dụng gang tay, bước chân hoặc thước kẻ để đo các vật dụng gần gũi.",
        "Bài 28. Luyện tập chung": "Ôn tập về số đến 100 và đo lường.",
        "Bài 29. Phép cộng số có hai chữ số với số có một chữ số": "Cách đặt tính rồi tính: Cộng hàng đơn vị trước, hàng chục giữ nguyên.",
        "Bài 30. Phép cộng số có hai chữ số với số có hai chữ số": "Cộng đơn vị với đơn vị, chục với chục.",
        "Bài 31. Phép trừ số có hai chữ số cho số có một chữ số": "Trừ hàng đơn vị, giữ nguyên hàng chục.",
        "Bài 32. Phép trừ số có hai chữ số cho số có hai chữ số": "Trừ đơn vị cho đơn vị, chục cho chục.",
        "Bài 33. Luyện tập chung": "Thực hành các phép tính không nhớ trong phạm vi 100.",
        "Bài 34. Xem giờ đúng trên đồng hồ": "Nhận biết kim giờ và kim phút. Cách đọc giờ khi kim phút chỉ số 12.",
        "Bài 35. Các ngày trong tuần": "Nhận biết tên gọi và thứ tự 7 ngày trong một tuần.",
        "Bài 36. Thực hành xem kim đồng hồ và lịch": "Kết hợp xem giờ và xác định ngày tháng trên tờ lịch.",
        "Bài 37. Luyện tập chung": "Ôn tập kiến thức về thời gian.",
        "Bài 38. Ôn tập các số và phép tính trong phạm vi 10": "Hệ thống lại kiến thức cơ bản nhất về số học.",
        "Bài 39. Ôn tập các số và phép tính trong phạm vi 100": "Tổng ôn các kỹ năng tính toán không nhớ.",
        "Bài 40. Ôn tập hình học và đo lường": "Ôn tập về hình dáng, độ dài và thời gian.",
        "Bài 41. Ôn tập chung": "Tổng kết toàn bộ chương trình Toán lớp 1."
    },
    2: {
        # --- TẬP 1: Bài 1 - Bài 36 ---
        "Bài 1. Ôn tập các số đến 100": "Ôn tập cách đọc, viết, so sánh và cấu tạo số chục - đơn vị.",
        "Bài 2. Tia số. Số liền trước, số liền sau": "Số liền trước = Số đã cho - 1; Số liền sau = Số đã cho + 1.",
        "Bài 3. Các thành phần của phép cộng, phép trừ": "Số hạng + Số hạng = Tổng; Số bị trừ - Số trừ = Hiệu.",
        "Bài 4. Hơn, kém nhau bao nhiêu": "Muốn tìm phần hơn/kém, ta lấy số lớn trừ số bé.",
        "Bài 5. Ôn tập phép cộng, trừ không nhớ": "Đặt tính thẳng cột, thực hiện từ phải sang trái.",
        "Bài 6. Luyện tập chung": "Củng cố kỹ năng tính toán và so sánh trong phạm vi 100.",
        "Bài 7. Phép cộng (qua 10) trong phạm vi 20": "Tách số để cộng cho đủ 10 rồi cộng với số còn lại.",
        "Bài 8. Bảng cộng (qua 10)": "Ghi nhớ các phép cộng có tổng lớn hơn 10 (ví dụ: 9+2=11).",
        "Bài 9. Bài toán về thêm, bớt một số đơn vị": "Thêm thì dùng phép cộng, bớt thì dùng phép trừ.",
        "Bài 10. Luyện tập chung": "Ôn tập bảng cộng và giải toán lời văn.",
        "Bài 11. Phép trừ (qua 10) trong phạm vi 20": "Trừ để được 10 rồi trừ tiếp số đơn vị còn lại.",
        "Bài 12. Bảng trừ (qua 10)": "Ghi nhớ các phép trừ phạm vi 20 (ví dụ: 11-2=9).",
        "Bài 13. Bài toán về nhiều hơn, ít hơn một số đơn vị": "Phân tích từ khóa 'nhiều hơn', 'ít hơn' để chọn phép tính đúng.",
        "Bài 14. Luyện tập chung": "Ôn tập bảng trừ và kỹ năng giải toán.",
        "Bài 15. Ki-lô-gam": "Ki-lô-gam (kg) là đơn vị đo khối lượng. 1 kg đọc là một ki-lô-gam.",
        "Bài 16. Lít": "Lít (l) là đơn vị đo dung tích chất lỏng. 1 l đọc là một lít.",
        "Bài 17. Thực hành đo kg, lít": "Sử dụng cân và ca đong để đo khối lượng và dung tích thực tế.",
        "Bài 18. Luyện tập chung": "Ôn tập tổng hợp về đơn vị đo lường.",
        "Bài 19. Phép cộng (có nhớ) số có 2 chữ số với số có 1 chữ số": "Cộng hàng đơn vị, nhớ 1 chục sang hàng chục.",
        "Bài 20. Phép cộng (có nhớ) số có 2 chữ số với số có 2 chữ số": "Cộng đơn vị nhớ sang chục, rồi cộng các chữ số hàng chục.",
        "Bài 21. Luyện tập chung": "Thực hành phép cộng có nhớ phạm vi 100.",
        "Bài 22. Phép trừ (có nhớ) số có 2 chữ số cho số có 1 chữ số": "Mượn 1 chục ở hàng chục khi hàng đơn vị không trừ được.",
        "Bài 23. Phép trừ (có nhớ) số có 2 chữ số cho số có 2 chữ số": "Thực hiện trừ đơn vị (có mượn) rồi trừ hàng chục.",
        "Bài 24. Luyện tập chung": "Thực hành phép trừ có nhớ phạm vi 100.",
        "Bài 25. Điểm, đoạn thẳng, đường thẳng, đường cong": "Nhận diện các hình cơ bản; ba điểm thẳng hàng cùng nằm trên một đường thẳng.",
        "Bài 26. Đường gấp khúc. Hình tứ giác": "Độ dài đường gấp khúc bằng tổng độ dài các đoạn thẳng thành phần.",
        "Bài 27. Thực hành gấp, cắt, ghép hình": "Sáng tạo hình ảnh từ các hình học cơ bản.",
        "Bài 28. Luyện tập chung": "Ôn tập nhận diện hình học và tính độ dài.",
        "Bài 29. Ngày - giờ, giờ - phút": "1 giờ = 60 phút. Kim phút chỉ số 12 là giờ đúng, số 6 là giờ rưỡi.",
        "Bài 30. Ngày - tháng": "Biết cách xem lịch để xác định ngày trong tuần và ngày trong tháng.",
        "Bài 31. Thực hành xem đồng hồ, xem lịch": "Ứng dụng thời gian vào các hoạt động sinh hoạt hằng ngày.",
        "Bài 32. Luyện tập chung": "Ôn tập kiến thức về thời gian và đo lường.",
        "Bài 33. Ôn tập phép cộng, trừ phạm vi 20, 100": "Tổng ôn các bảng tính và kỹ năng đặt tính.",
        "Bài 34. Ôn tập hình phẳng": "Củng cố kiến thức về điểm, đoạn thẳng, hình tứ giác.",
        "Bài 35. Ôn tập đo lường": "Ôn tập các đơn vị: cm, m, kg, l và thời gian.",
        "Bài 36. Ôn tập chung": "Tổng kết kiến thức học kỳ 1.",

        # --- TẬP 2: Bài 37 - Bài 75 ---
        "Bài 37. Phép nhân": "Phép nhân là tổng của các số hạng bằng nhau. Ví dụ: 2 + 2 + 2 = 2 x 3.",
        "Bài 38. Thừa số, tích": "Trong phép nhân a x b = c: a và b là thừa số, c là tích.",
        "Bài 39. Bảng nhân 2": "Tích tăng thêm 2 đơn vị khi thừa số thứ hai tăng thêm 1.",
        "Bài 40. Bảng nhân 5": "Các tích trong bảng nhân 5 luôn tận cùng là 0 hoặc 5.",
        "Bài 41. Phép chia": "Phép chia là phép tính ngược của phép nhân để chia đều một nhóm.",
        "Bài 42. Số bị chia, số chia, thương": "Trong a : b = c: a là số bị chia, b là số chia, c là thương.",
        "Bài 43. Bảng chia 2": "Dựa vào bảng nhân 2 để tìm kết quả phép chia cho 2.",
        "Bài 44. Bảng chia 5": "Dựa vào bảng nhân 5 để tìm kết quả phép chia cho 5.",
        "Bài 45. Luyện tập chung": "Ôn tập mối quan hệ giữa phép nhân và phép chia.",
        "Bài 46. Khối trụ, khối cầu": "Khối trụ có hai mặt đáy hình tròn; khối cầu có dạng tròn đều như quả bóng.",
        "Bài 47. Luyện tập chung": "Phân biệt khối trụ, khối cầu và khối lập phương, khối hộp chữ nhật.",
        "Bài 48. Đơn vị, chục, trăm, nghìn": "10 đơn vị = 1 chục; 10 chục = 1 trăm; 10 trăm = 1 nghìn.",
        "Bài 49. Các số tròn trăm, tròn chục": "Số tròn trăm có tận cùng là 00; số tròn chục có tận cùng là 0.",
        "Bài 50. So sánh các số tròn trăm, tròn chục": "So sánh chữ số hàng trăm, sau đó đến hàng chục.",
        "Bài 51. Số có ba chữ số": "Gồm hàng trăm, hàng chục và hàng đơn vị. Ví dụ: 123.",
        "Bài 52. Viết số thành tổng": "Ví dụ: 345 = 300 + 40 + 5.",
        "Bài 53. So sánh các số có ba chữ số": "So sánh từ trái sang phải: hàng trăm -> hàng chục -> hàng đơn vị.",
        "Bài 54. Luyện tập chung": "Ôn tập cấu tạo và so sánh số có ba chữ số.",
        "Bài 55. Ki-lô-mét": "Ki-lô-mét (km) là đơn vị đo độ dài lớn. 1 km = 1000 m.",
        "Bài 56. Mét": "Mét (m) là đơn vị đo độ dài. 1 m = 10 dm = 100 cm.",
        "Bài 57. Mi-li-mét": "Mi-li-mét (mm) là đơn vị đo độ dài rất nhỏ. 1 cm = 10 mm.",
        "Bài 58. Tiền Việt Nam": "Làm quen với các tờ tiền: 100đ, 200đ, 500đ, 1000đ, 2000đ, 5000đ.",
        "Bài 59. Luyện tập chung": "Ôn tập về đo độ dài và tiền tệ.",
        "Bài 60. Phép cộng (không nhớ) trong phạm vi 1000": "Cộng lần lượt hàng đơn vị, hàng chục, hàng trăm.",
        "Bài 61. Phép trừ (không nhớ) trong phạm vi 1000": "Trừ lần lượt hàng đơn vị, hàng chục, hàng trăm.",
        "Bài 62. Luyện tập chung": "Thực hành tính toán không nhớ trong phạm vi 1000.",
        "Bài 63. Phép cộng (có nhớ) trong phạm vi 1000": "Nếu hàng đơn vị/chục có tổng >= 10, ta nhớ sang hàng bên trái.",
        "Bài 64. Phép trừ (có nhớ) trong phạm vi 1000": "Mượn ở hàng bên trái nếu hàng hiện tại không trừ được.",
        "Bài 65. Luyện tập chung": "Thực hành tính toán có nhớ trong phạm vi 1000.",
        "Bài 66. Chắc chắn, có thể, không thể": "Dự đoán khả năng xảy ra của một sự kiện dựa trên dữ kiện.",
        "Bài 67. Thực hành trải nghiệm": "Thu thập dữ liệu và dự đoán kết quả thực tế.",
        "Bài 68. Biểu đồ tranh": "Đọc thông tin qua các biểu tượng hình ảnh trên biểu đồ.",
        "Bài 69. Kiểm đếm số liệu": "Đếm và ghi lại số lượng của các nhóm đối tượng khác nhau.",
        "Bài 70. Luyện tập chung": "Ôn tập về thống kê và xác suất đơn giản.",
        "Bài 71. Ôn tập các số trong phạm vi 1000": "Hệ thống lại cấu tạo và thứ tự số.",
        "Bài 72. Ôn tập phép cộng, phép trừ": "Ôn luyện các kỹ năng tính toán trong cả năm học.",
        "Bài 73. Ôn tập phép nhân, phép chia": "Ôn tập bảng nhân/chia 2 và 5.",
        "Bài 74. Ôn tập hình học và đo lường": "Tổng hợp về hình khối, độ dài, thời gian và tiền tệ.",
        "Bài 75. Ôn tập chung": "Tổng ôn kiến thức cuối năm lớp 2."
    },
3: {
        # --- TẬP 1 ---
        "Bài 1. Ôn tập các số đến 1000": "Ôn tập đọc, viết, so sánh và cấu tạo số hàng trăm, chục, đơn vị.",
        "Bài 2. Ôn tập phép cộng, phép trừ trong phạm vi 1000": "Củng cố kỹ năng đặt tính và thực hiện tính cộng, trừ có nhớ hoặc không nhớ.",
        "Bài 3. Tìm thành phần trong phép cộng, phép trừ": "Muốn tìm số hạng chưa biết lấy Tổng trừ đi số hạng đã biết. Muốn tìm số bị trừ lấy Hiệu cộng với số trừ.",
        "Bài 4. Ôn tập bảng nhân 2; 5, bảng chia 2; 5": "Hệ thống lại các phép tính nhẩm cơ bản trong bảng 2 và 5.",
        "Bài 5. Bảng nhân 3, bảng chia 3": "Hình thành phép nhân 3 và phép chia tương ứng.",
        "Bài 6. Bảng nhân 4, bảng chia 4": "Hình thành phép nhân 4 và phép chia tương ứng.",
        "Bài 7. Ôn tập hình học và đo lường": "Ôn lại nhận biết hình dạng và các đơn vị đo mm, cm, dm, m, km.",
        "Bài 8. Luyện tập chung": "Ôn tập tổng hợp các kiến thức đầu năm lớp 3.",
        "Bài 9. Bảng nhân 6, bảng chia 6": "Học thuộc lòng bảng nhân 6 và bảng chia 6.",
        "Bài 10. Bảng nhân 7, bảng chia 7": "Học thuộc lòng bảng nhân 7 và bảng chia 7.",
        "Bài 11. Bảng nhân 8, bảng chia 8": "Học thuộc lòng bảng nhân 8 và bảng chia 8.",
        "Bài 12. Bảng nhân 9, bảng chia 9": "Học thuộc lòng bảng nhân 9 và bảng chia 9.",
        "Bài 13. Tìm thành phần trong phép nhân, phép chia": "Muốn tìm thừa số chưa biết lấy Tích chia cho thừa số đã biết.",
        "Bài 14. Một phần mấy": "Nhận biết các phần bằng nhau của một đơn vị (1/2, 1/3, 1/4... 1/9).",
        "Bài 15. Luyện tập chung": "Củng cố kiến thức về bảng nhân, chia từ 6 đến 9.",
        "Bài 16. Điểm ở giữa, trung điểm của đoạn thẳng": "Trung điểm là điểm nằm chính giữa và chia đoạn thẳng thành hai phần bằng nhau.",
        "Bài 17. Hình tròn. Tâm, bán kính, đường kính": "Tâm là điểm chính giữa, đường kính dài gấp đôi bán kính.",
        "Bài 18. Góc, góc vuông, góc không vuông": "Sử dụng ê-ke để kiểm tra và nhận biết các loại góc.",
        "Bài 19. Hình tam giác, tứ giác, hình chữ nhật, hình vuông": "Đặc điểm về cạnh và góc của các hình phẳng.",
        "Bài 20. Thực hành vẽ hình, tạo hình": "Sử dụng thước và ê-ke để vẽ các hình đã học.",
        "Bài 21. Khối lập phương, khối hộp chữ nhật": "Đếm số mặt, số đỉnh và số cạnh của các khối hình.",
        "Bài 22. Luyện tập chung": "Ôn tập tổng hợp về hình học.",
        "Bài 23. Nhân số có hai chữ số với số có một chữ số": "Nhân lần lượt từ phải sang trái (hàng đơn vị rồi đến hàng chục).",
        "Bài 24. Gấp một số lên một số lần": "Muốn gấp một số lên nhiều lần, ta lấy số đó nhân với số lần.",
        "Bài 25. Phép chia hết, phép chia có dư": "Số dư luôn bé hơn số chia.",
        "Bài 26. Chia số có hai chữ số cho số có một chữ số": "Thực hiện chia từ trái sang phải (hàng chục rồi đến hàng đơn vị).",
        "Bài 27. Giảm một số đi một số lần": "Muốn giảm một số đi nhiều lần, ta lấy số đó chia cho số lần.",
        "Bài 28. Bài toán giải bằng hai bước tính": "Phân tích để giải quyết bài toán qua hai phép tính liên tiếp.",
        "Bài 29. Luyện tập chung": "Ôn tập nhân chia số có 2 chữ số và giải toán.",
        "Bài 30. Mi-li-mét": "Đơn vị đo độ dài. 1 cm = 10 mm.",
        "Bài 31. Gam": "Đơn vị đo khối lượng. 1 kg = 1000 g.",
        "Bài 32. Mi-li-lít": "Đơn vị đo dung tích. 1 l = 1000 ml.",
        "Bài 33. Nhiệt độ. Đơn vị đo nhiệt độ": "Làm quen với độ C và nhiệt kế.",
        "Bài 34. Luyện tập chung": "Ôn tập các đơn vị đo lường mới học.",
        "Bài 35. Luyện tập chung": "Tổng hợp các kỹ năng tính toán và đo lường.",
        "Bài 36. Nhân số có ba chữ số với số có một chữ số": "Nhân từ phải sang trái (đơn vị -> chục -> trăm). Chú ý phần có nhớ.",
        "Bài 37. Chia số có ba chữ số cho số có một chữ số": "Chia lần lượt từ hàng trăm xuống.",
        "Bài 38. Biểu thức số. Tính giá trị biểu thức": "Thứ tự: Trong ngoặc trước -> Nhân chia -> Cộng trừ.",
        "Bài 39. So sánh số lớn gấp mấy lần số bé": "Lấy số lớn chia cho số bé.",
        "Bài 40. Tìm số chia": "Số chia = Số bị chia : Thương.",
        "Bài 41. Luyện tập chung": "Ôn tập về biểu thức và tìm thành phần phép tính.",
        "Bài 42. Ôn tập biểu thức số": "Củng cố quy tắc tính giá trị biểu thức.",
        "Bài 43. Ôn tập hình học và đo lường": "Hệ thống lại kiến thức học kỳ 1.",
        "Bài 44. Ôn tập chung": "Tổng kết cuối học kỳ 1 lớp 3.",

        # --- TẬP 2 ---
        "Bài 45. Các số có bốn chữ số. Số 10 000": "Đọc, viết các số gồm hàng nghìn, trăm, chục, đơn vị.",
        "Bài 46. So sánh các số trong phạm vi 10 000": "So sánh từ hàng nghìn, nếu bằng nhau so sánh đến hàng trăm...",
        "Bài 47. Làm quen với chữ số La Mã": "Cách viết và đọc các số I, V, X đến XX.",
        "Bài 48. Làm tròn số đến hàng chục, hàng trăm": "Quy tắc làm tròn số dựa vào chữ số hàng kế bên.",
        "Bài 49. Luyện tập chung": "Ôn tập về số có 4 chữ số.",
        "Bài 50. Chu vi hình tam giác, hình tứ giác, hình chữ nhật, hình vuông": "Chu vi là tổng độ dài các cạnh của hình đó.",
        "Bài 51. Diện tích của một hình. Xăng-ti-mét vuông": "Diện tích là phần mặt phẳng được bao phủ. Đơn vị cm².",
        "Bài 52. Diện tích hình chữ nhật, diện tích hình vuông": "S chữ nhật = Dài x Rộng; S vuông = Cạnh x Cạnh.",
        "Bài 53. Luyện tập chung": "Ôn tập chu vi và diện tích.",
        "Bài 54. Phép cộng trong phạm vi 10 000": "Đặt tính cộng có nhớ đến hàng nghìn.",
        "Bài 55. Phép trừ trong phạm vi 10 000": "Đặt tính trừ có nhớ đến hàng nghìn.",
        "Bài 56. Nhân số có bốn chữ số với số có một chữ số": "Quy tắc nhân tương tự số có 3 chữ số.",
        "Bài 57. Chia số có bốn chữ số cho số có một chữ số": "Thực hiện chia từ hàng nghìn trở xuống.",
        "Bài 58. Luyện tập chung": "Củng cố 4 phép tính trong phạm vi 10 000.",
        "Bài 59. Các số có năm chữ số. Số 100 000": "Nhận biết hàng chục nghìn.",
        "Bài 60. So sánh các số trong phạm vi 100 000": "Thứ tự so sánh từ trái sang phải.",
        "Bài 61. Làm tròn số đến hàng nghìn, hàng chục nghìn": "Mở rộng quy tắc làm tròn cho số lớn.",
        "Bài 62. Luyện tập chung": "Ôn tập số đến 100 000.",
        "Bài 63. Phép cộng trong phạm vi 100 000": "Cộng các số có 5 chữ số.",
        "Bài 64. Phép trừ trong phạm vi 100 000": "Trừ các số có 5 chữ số.",
        "Bài 65. Luyện tập chung": "Luyện tập cộng, trừ trong phạm vi 100 000.",
        "Bài 66. Xem đồng hồ. Tháng - Năm": "1 năm có 12 tháng. Tháng có 28, 29, 30 hoặc 31 ngày.",
        "Bài 67. Thực hành xem đồng hồ, xem lịch": "Ứng dụng tính khoảng thời gian giữa hai thời điểm.",
        "Bài 68. Tiền Việt Nam": "Nhận biết và tính toán với các tờ tiền mệnh giá đến 100 000 đồng.",
        "Bài 69. Luyện tập chung": "Ôn tập thời gian và tiền tệ.",
        "Bài 70. Nhân số có năm chữ số với số có một chữ số": "Đặt tính nhân số có 5 chữ số.",
        "Bài 71. Chia số có năm chữ số cho số có một chữ số": "Thực hiện chia số có 5 chữ số.",
        "Bài 72. Luyện tập chung": "Luyện tập nhân, chia trong phạm vi 100 000.",
        "Bài 73. Thu thập, phân loại, ghi chép số liệu": "Làm quen với bảng số liệu thống kê.",
        "Bài 74. Khả năng xảy ra của một sự kiện": "Sử dụng: Chắc chắn, Có thể, Không thể.",
        "Bài 75. Thực hành và trải nghiệm thu thập số liệu": "Thu thập dữ liệu từ các hoạt động thực tế.",
        "Bài 76. Ôn tập các số trong phạm vi 10 000, 100 000": "Hệ thống lại cấu tạo số.",
        "Bài 77. Ôn tập phép cộng, phép trừ": "Tổng hợp kỹ năng cộng trừ cả năm.",
        "Bài 78. Ôn tập phép nhân, phép chia": "Tổng hợp kỹ năng nhân chia cả năm.",
        "Bài 79. Ôn tập hình học và đo lường": "Ôn tập diện tích, chu vi và các đơn vị đo.",
        "Bài 80. Ôn tập về một số yếu tố thống kê và xác suất": "Củng cố đọc biểu đồ và dự đoán sự kiện.",
        "Bài 81. Ôn tập chung": "Tổng ôn kiến thức cuối cấp lớp 3."
    },
4: {
        # --- TẬP 1 ---
        "Bài 1. Ôn tập các số đến 100 000": "Ôn tập cách đọc, viết và cấu tạo số trong phạm vi 5 chữ số.",
        "Bài 2. Ôn tập phép cộng, phép trừ trong phạm vi 100 000": "Củng cố kỹ năng đặt tính và tính cộng, trừ có nhớ.",
        "Bài 3. Ôn tập phép nhân, phép chia trong phạm vi 100 000": "Ôn tập nhân số có nhiều chữ số với số có một chữ số và chia tương ứng.",
        "Bài 4. Biểu thức chữ": "Làm quen với biểu thức chứa một chữ (ví dụ: a + 5) và tính giá trị của nó.",
        "Bài 5. Giải bài toán có ba bước tính": "Phân tích và giải quyết các bài toán phức tạp hơn qua ba bước tính.",
        "Bài 6. Luyện tập chung": "Ôn tập tổng hợp các kiến thức đầu năm lớp 4.",
        "Bài 7. Các số có sáu chữ số. Hàng và lớp": "Hàng đơn vị, chục, trăm thuộc lớp đơn vị; hàng nghìn, chục nghìn, trăm nghìn thuộc lớp nghìn.",
        "Bài 8. Tổng quát về số tự nhiên": "Dãy số tự nhiên bắt đầu từ 0. Không có số tự nhiên lớn nhất.",
        "Bài 9. So sánh các số có nhiều chữ số": "So sánh theo số các chữ số, sau đó so sánh từng hàng từ trái sang phải.",
        "Bài 10. Số tròn chục, tròn trăm, tròn nghìn, tròn chục nghìn": "Nhận biết và sử dụng các số tròn trong tính toán nhanh.",
        "Bài 11. Làm tròn số đến hàng nghìn, chục nghìn, trăm nghìn": "Áp dụng quy tắc làm tròn cho các số lớn.",
        "Bài 12. Các số trong phạm vi lớp Triệu": "Làm quen với lớp triệu (hàng triệu, chục triệu, trăm triệu).",
        "Bài 13. Làm tròn số đến hàng triệu": "Quy tắc làm tròn số trong phạm vi lớp triệu.",
        "Bài 14. So sánh các số trong phạm vi lớp Triệu": "Mở rộng quy tắc so sánh cho các số đến 9 chữ số.",
        "Bài 15. Luyện tập chung": "Củng cố kiến thức về số có nhiều chữ số và lớp triệu.",
        "Bài 16. Luyện tập chung": "Ôn tập tổng hợp về hàng, lớp và so sánh số.",
        "Bài 17. Yến, tạ, tấn": "Các đơn vị đo khối lượng lớn. 1 tấn = 10 tạ = 100 yến = 1000 kg.",
        "Bài 18. Giây, thế kỷ": "1 phút = 60 giây; 1 thế kỷ = 100 năm.",
        "Bài 19. Giây, thế kỷ (tiếp theo)": "Thực hành chuyển đổi các đơn vị thời gian.",
        "Bài 20. Thực hành và trải nghiệm sử dụng một số đơn vị đo": "Ứng dụng các đơn vị đo khối lượng và thời gian vào thực tế.",
        "Bài 21. Luyện tập chung": "Ôn tập tổng hợp về đo lường (yến, tạ, tấn, giây, thế kỷ).",
        "Bài 22. Phép cộng các số có nhiều chữ số": "Đặt tính và tính cộng các số có đến 6 chữ số.",
        "Bài 23. Phép trừ các số có nhiều chữ số": "Đặt tính và tính trừ các số có đến 6 chữ số.",
        "Bài 24. Tính chất giao hoán và kết hợp của phép cộng": "a + b = b + a; (a + b) + c = a + (b + c).",
        "Bài 25. Tìm hai số khi biết tổng và hiệu của hai số đó": "Số lớn = (Tổng + Hiệu) : 2; Số bé = (Tổng - Hiệu) : 2.",
        "Bài 26. Luyện tập chung": "Thực hành giải toán về tổng - hiệu và các phép tính cộng, trừ.",
        "Bài 27. Hai đường thẳng vuông góc. Vẽ hai đường thẳng vuông góc": "Hai đường thẳng cắt nhau tạo thành 4 góc vuông.",
        
        "Bài 28. Hai đường thẳng song song. Vẽ hai đường thẳng song song": "Hai đường thẳng không bao giờ cắt nhau dù kéo dài mãi.",
        "Bài 29. Đường cao của hình tam giác": "Đoạn thẳng hạ vuông góc từ đỉnh xuống cạnh đối diện.",
        "Bài 30. Thực hành và trải nghiệm vẽ hai đường thẳng song song": "Sử dụng thước và ê-ke để vẽ hình.",
        "Bài 31. Hình bình hành": "Hình có hai cặp cạnh đối diện song song và bằng nhau.",
        "Bài 32. Hình thoi": "Hình có bốn cạnh bằng nhau và hai cặp cạnh đối diện song song.",
        "Bài 33. Luyện tập chung": "Ôn tập nhận diện và tính chất các hình phẳng mới học.",
        "Bài 34. Ba góc: góc nhọn, góc tù, góc bẹt": "Góc nhọn < Góc vuông; Góc vuông < Góc tù < Góc bẹt (180 độ).",
        "Bài 35. Luyện tập chung": "Củng cố kiến thức về góc và hình học.",
        "Bài 36. Ôn tập học kỳ 1": "Hệ thống hóa toàn bộ kiến thức nửa đầu năm lớp 4.",
        "Bài 37. Ôn tập chung": "Tổng ôn các kỹ năng tính toán và giải toán học kỳ 1.",

        # --- TẬP 2: Bài 38 - Bài 73 ---
        "Bài 38. Nhân với số có một chữ số": "Thực hiện nhân lần lượt từ phải sang trái các số có nhiều chữ số.",
        "Bài 39. Nhân với 10, 100, 1000,... Chia cho 10, 100, 1000,...": "Thêm hoặc bớt các chữ số 0 vào bên phải của số đó.",
        "Bài 40. Tính chất giao hoán và kết hợp của phép nhân": "a x b = b x a; (a x b) x c = a x (b x c).",
        "Bài 41. Nhân với số có hai chữ số": "Tính tích riêng thứ nhất và tích riêng thứ hai (lùi sang trái 1 cột).",
        "Bài 42. Luyện tập chung": "Thực hành kỹ năng nhân số có hai chữ số.",
        "Bài 43. Chia cho số có một chữ số": "Thực hiện chia từ trái sang phải, mỗi bước thực hiện Chia - Nhân - Trừ.",
        "Bài 44. Chia cho 10, 100, 1000,...": "Xóa bớt số 0 ở tận cùng của số bị chia.",
        "Bài 45. Thực hiện phép chia cho số có hai chữ số": "Cách ước lượng thương khi chia cho số có hai chữ số.",
        "Bài 46. Luyện tập chung": "Củng cố kỹ năng chia cho số có hai chữ số.",
        "Bài 47. Luyện tập chung": "Tổng hợp các kỹ năng nhân và chia.",
        "Bài 48. Phân số và phép chia số tự nhiên": "Phân số a/b có thể coi là thương của phép chia a : b.",
        "Bài 49. Phân số bằng nhau": "Nếu nhân hoặc chia cả tử và mẫu với cùng một số khác 0 thì được phân số mới bằng phân số cũ.",
        "Bài 50. Rút gọn phân số": "Chia cả tử và mẫu cho cùng một số tự nhiên lớn hơn 1 để được phân số đơn giản hơn.",
        "Bài 51. Quy đồng mẫu số các phân số": "Đưa các phân số về cùng một mẫu số để dễ so sánh và tính toán.",
        "Bài 52. So sánh hai phân số cùng mẫu số": "Phân số nào có tử số lớn hơn thì lớn hơn.",
        "Bài 53. So sánh hai phân số khác mẫu số": "Quy đồng mẫu số rồi so sánh các tử số.",
        "Bài 54. Luyện tập chung": "Ôn tập các tính chất cơ bản của phân số.",
        "Bài 55. Phép cộng phân số": "Cộng các tử số và giữ nguyên mẫu số (quy đồng nếu khác mẫu).",
        "Bài 56. Phép trừ phân số": "Trừ các tử số và giữ nguyên mẫu số (quy đồng nếu khác mẫu).",
        "Bài 57. Luyện tập chung": "Thực hành cộng, trừ phân số.",
        "Bài 58. Phép nhân phân số": "Lấy tử số nhân với tử số, mẫu số nhân với mẫu số.",
        "Bài 59. Phép chia phân số": "Lấy phân số thứ nhất nhân với phân số thứ hai đảo ngược.",
        "Bài 60. Luyện tập chung": "Thực hành nhân, chia phân số.",
        "Bài 61. Luyện tập chung": "Tổng hợp 4 phép tính với phân số.",
        "Bài 62. Tìm phân số của một số": "Muốn tìm a/b của số m, ta lấy m nhân với a/b.",
        "Bài 63. Giải bài toán có lời văn liên quan đến phân số": "Áp dụng các phép tính phân số vào thực tế.",
        "Bài 64. Lập biểu đồ tranh": "Sử dụng hình ảnh để biểu diễn số liệu thống kê.",
        "Bài 65. Biểu đồ cột": "Sử dụng các cột có độ cao khác nhau để biểu thị số liệu.",
        
        "Bài 66. Trung bình cộng": "Muốn tìm số trung bình cộng, ta lấy tổng các số chia cho số các số hạng đó.",
        "Bài 67. Tìm hai số khi biết tổng và tỉ số của hai số đó": "Vẽ sơ đồ, tìm tổng số phần bằng nhau, tìm giá trị một phần.",
        "Bài 68. Tìm hai số khi biết hiệu và tỉ số của hai số đó": "Vẽ sơ đồ, tìm hiệu số phần bằng nhau, tìm giá trị một phần.",
        "Bài 69. Luyện tập chung": "Ôn tập các bài toán về tỉ số.",
        "Bài 70. Ôn tập số tự nhiên và các phép tính": "Tổng ôn kiến thức về số học.",
        "Bài 71. Ôn tập phân số và các phép tính": "Tổng ôn kiến thức về phân số.",
        "Bài 72. Ôn tập hình học và đo lường": "Tổng ôn kiến thức về diện tích, chu vi và các loại hình.",
        "Bài 73. Ôn tập chung": "Tổng kết kiến thức toàn bộ chương trình Toán lớp 4."

    },
5:  {
        # --- TẬP 1: Bài 1 ---
        "Bài 1. Ôn tập số tự nhiên": "Ôn tập đọc, viết, so sánh và các tính chất của số tự nhiên.",
        "Bài 2. Ôn tập các phép tính với số tự nhiên": "Củng cố kỹ năng cộng, trừ, nhân, chia số tự nhiên.",
        "Bài 3. Ôn tập phân số": "Ôn tập khái niệm, tính chất cơ bản và rút gọn phân số.",
        "Bài 4. Phân số thập phân": "Phân số có mẫu số là 10, 100, 1000... Ví dụ: 3/10, 15/100.",
        "Bài 5. Ôn tập các phép tính với phân số": "Cộng, trừ, nhân, chia phân số (quy đồng mẫu số nếu cần).",
        "Bài 6. Cộng, trừ hai phân số khác mẫu số": "Quy đồng mẫu số rồi thực hiện cộng hoặc trừ tử số.",
        "Bài 7. Hỗn số": "Gồm phần nguyên và phần phân số. Ví dụ: 2 và 3/4.",
        "Bài 8. Ôn tập hình học và đo lường": "Ôn tập về chu vi, diện tích các hình đã học ở lớp 4.",
        "Bài 9. Luyện tập chung": "Tổng hợp kiến thức về phân số và hỗn số.",
        "Bài 10. Khái niệm số thập phân": "Cách viết mới của phân số thập phân. Ví dụ: 0,1; 0,01.",
        "Bài 11. Hàng của số thập phân. Đọc, viết số thập phân": "Phần nguyên và phần thập phân ngăn cách bởi dấu phẩy.",
        "Bài 12. Viết số đo đại lượng dưới dạng số thập phân": "Chuyển đổi các đơn vị đo độ dài, khối lượng sang số thập phân.",
        "Bài 13. Làm tròn số thập phân": "Quy tắc làm tròn đến hàng đơn vị, hàng phần mười, hàng phần trăm.",
        "Bài 14. So sánh hai số thập phân": "So sánh phần nguyên trước, sau đó so sánh từng hàng ở phần thập phân.",
        "Bài 15. Luyện tập chung": "Củng cố cách đọc, viết và so sánh số thập phân.",
        "Bài 16. Phép cộng số thập phân": "Đặt tính thẳng cột dấu phẩy, cộng như số tự nhiên.",
        "Bài 17. Phép trừ số thập phân": "Đặt tính thẳng cột dấu phẩy, trừ như số tự nhiên.",
        "Bài 18. Luyện tập chung": "Thực hành cộng, trừ số thập phân.",
        "Bài 19. Nhân một số thập phân với một số tự nhiên": "Nhân như số tự nhiên, đếm chữ số thập phân để đặt dấu phẩy ở tích.",
        "Bài 20. Nhân một số thập phân với 10, 100, 1000...": "Dịch dấu phẩy sang bên phải 1, 2, 3... chữ số.",
        "Bài 21. Nhân một số thập phân với một số thập phân": "Thực hiện nhân và đếm tổng số chữ số thập phân của cả hai thừa số.",
        "Bài 22. Luyện tập chung": "Thực hành các phép tính nhân với số thập phân.",
        "Bài 23. Chia một số thập phân cho một số tự nhiên": "Chia phần nguyên trước, viết dấu phẩy vào thương rồi chia tiếp phần thập phân.",
        "Bài 24. Chia một số tự nhiên cho một số tự nhiên mà thương là số thập phân": "Khi chia dư, viết dấu phẩy vào thương và thêm 0 vào số dư để chia tiếp.",
        "Bài 25. Chia một số tự nhiên cho một số thập phân": "Bỏ dấu phẩy ở số chia, thêm số chữ số 0 tương ứng vào số bị chia rồi chia.",
        "Bài 26. Chia một số thập phân cho một số thập phân": "Dịch dấu phẩy ở cả hai số rồi thực hiện phép chia.",
        "Bài 27. Luyện tập chung": "Củng cố kỹ năng chia số thập phân.",
        "Bài 28. Thang nhiệt độ Xen-xi-út. Thang nhiệt độ Farenhai": "Làm quen với độ C và độ F.",
        "Bài 29. Tỉ số phần trăm": "Phân số có mẫu số là 100 được viết dưới dạng %. Ví dụ: 25%.",
        "Bài 30. Giải toán về tỉ số phần trăm": "Tìm giá trị phần trăm của một số và ngược lại.",
        "Bài 31. Giải toán về tỉ số phần trăm (tiếp theo)": "Tìm tỉ số phần trăm của hai số.",
        "Bài 32. Luyện tập chung": "Thực hành giải toán tỉ số phần trăm thực tế.",
        "Bài 33. Ôn tập học kỳ 1": "Hệ thống kiến thức về số thập phân và các phép tính.",
        "Bài 34. Ôn tập hình học và đo lường học kỳ 1": "Ôn tập đơn vị đo và các bài toán thực tế.",
        "Bài 35. Ôn tập chung": "Tổng kết học kỳ 1.",

        # --- TẬP 2: Bài 36 - Bài 72 ---
        "Bài 36. Hình tam giác. Diện tích hình tam giác": "S = (Đáy x Chiều cao) : 2.",
        
        "Bài 37. Hình thang. Diện tích hình thang": "S = (Đáy lớn + Đáy bé) x Chiều cao : 2.",
        "Bài 38. Hình tròn. Chu vi và diện tích hình tròn": "C = d x 3,14; S = r x r x 3,14.",
        
        "Bài 39. Luyện tập chung": "Ôn tập diện tích các hình phẳng.",
        "Bài 40. Hình hộp chữ nhật. Hình lập phương": "Nhận biết các mặt, cạnh, đỉnh và đặc điểm của hai khối hình.",
        "Bài 41. Diện tích xung quanh và diện tích toàn phần hình hộp chữ nhật": "Sxq = Chu vi đáy x Chiều cao; Stp = Sxq + S2đáy.",
        "Bài 42. Diện tích xung quanh và diện tích toàn phần hình lập phương": "Sxq = (Cạnh x Cạnh) x 4; Stp = (Cạnh x Cạnh) x 6.",
        "Bài 43. Luyện tập chung": "Thực hành tính diện tích các hình khối.",
        "Bài 44. Hình trụ. Hình cầu": "Nhận diện hình trụ và hình cầu trong thực tế.",
        "Bài 45. Thể tích của một hình": "Khái niệm về không gian mà hình đó chiếm chỗ.",
        "Bài 46. Xăng-ti-mét khối. Đề-xi-mét khối": "Các đơn vị đo thể tích. 1 dm3 = 1000 cm3.",
        "Bài 47. Mét khối": "1 m3 = 1000 dm3 = 1.000.000 cm3.",
        "Bài 48. Luyện tập chung": "Chuyển đổi các đơn vị đo thể tích.",
        "Bài 49. Thể tích hình hộp chữ nhật": "V = Dài x Rộng x Cao (cùng đơn vị đo).",
        "Bài 50. Thể tích hình lập phương": "V = Cạnh x Cạnh x Cạnh.",
        "Bài 51. Luyện tập chung": "Thực hành tính thể tích.",
        "Bài 52. Thực hành và trải nghiệm về đo lường": "Sử dụng các công cụ đo đạc thực tế.",
        "Bài 53. Bảng đơn vị đo thời gian": "Mối quan hệ giữa năm, tháng, tuần, ngày, giờ, phút, giây.",
        "Bài 54. Cộng, trừ số đo thời gian": "Thực hiện tính theo từng loại đơn vị thời gian.",
        "Bài 55. Nhân, chia số đo thời gian với một số": "Thực hiện tính và quy đổi nếu đơn vị nhỏ vượt quá giới hạn.",
        "Bài 56. Luyện tập chung": "Thực hành tính toán với thời gian.",
        "Bài 57. Vận tốc": "v = s : t. Đơn vị thường dùng là km/h, m/s.",
        "Bài 58. Quãng đường": "s = v x t.",
        "Bài 59. Thời gian": "t = s : v.",
        "Bài 60. Luyện tập chung": "Giải các bài toán về chuyển động đều.",
        "Bài 61. Chuyển động ngược chiều và cùng chiều": "Tìm thời gian gặp nhau của hai vật chuyển động.",
        "Bài 62. Luyện tập chung": "Nâng cao kỹ năng giải toán chuyển động.",
        "Bài 63. Thu thập, phân loại, sắp xếp các số liệu": "Kỹ năng cơ bản trong thống kê.",
        "Bài 64. Biểu đồ hình quạt tròn": "Đọc và phân tích tỉ lệ phần trăm trên biểu đồ tròn.",
        
        "Bài 65. Tỉ số của số lần lặp lại sự kiện so với tổng số lần": "Làm quen với xác suất thực nghiệm.",
        "Bài 66. Thực hành thu thập, phân tích số liệu thống kê": "Lập bảng và biểu đồ từ dữ liệu thực tế.",
        "Bài 67. Luyện tập chung": "Ôn tập về thống kê và xác suất.",
        "Bài 68. Ôn tập số tự nhiên, phân số, số thập phân": "Hệ thống lại các tập hợp số.",
        "Bài 69. Ôn tập các phép tính": "Tổng hợp kỹ năng tính toán cả cấp tiểu học.",
        "Bài 70. Ôn tập tỉ số, tỉ số phần trăm": "Củng cố các bài toán về tỉ số.",
        "Bài 71. Ôn tập hình học": "Ôn tập chu vi, diện tích, thể tích các hình đã học.",
        "Bài 72. Ôn tập đo lường": "Ôn tập các đơn vị đo độ dài, khối lượng, diện tích, thể tích, thời gian.",
        "Bài 73. Ôn tập toán chuyển động đều": "Hệ thống các công thức v, s, t.",
        "Bài 74. Ôn tập một số yếu tố thống kê và xác suất": "Tổng ôn về biểu đồ và xác suất.",
        "Bài 75. Ôn tập chung": "Bài tập tổng hợp cuối năm lớp 5."
    }
}

# 2. Danh sách tổng hợp tất cả bài học
# Chú ý: Title ở đây phải khớp 100% với Title trong theory_data
lessons = []
for grade, chapters in theory_data.items():
    for title in chapters.keys():
        # --- Logic tính XP tự động ---
        # Lớp 1: 10 XP, Lớp 2: 15 XP, Lớp 3: 20 XP...
        base_xp = 10 + (grade - 1) * 5
        
        # Thưởng thêm XP cho các bài khó hoặc bài tổng kết
        current_xp = base_xp
        if "Luyện tập" in title:
            current_xp += 5
        if "Ôn tập" in title:
            current_xp += 10
            
        # --- Logic gán lesson_id ---
        # Thông thường lesson_id sẽ đi theo khối lớp (Grade)
        lesson_id = grade
        
        # Thêm vào danh sách lessons
        lessons.append(LessonData(
            title=title, 
            grade=grade, 
            xp=current_xp, 
            lesson_id=lesson_id
        ))
def get_lessons_for_grade(grade):
    # Thay THEORY_DATABASE bằng theory_data
    lesson_titles = list(theory_data.get(grade, {}).keys())
    
    # Đảm bảo phần còn lại của hàm cũng sử dụng đúng tên biến
    lessons = []
    # Ví dụ nếu bạn có logic tạo danh sách LessonData ở đây:
    # for title in lesson_titles:
    #     lessons.append(LessonData(title, grade, 50, 0)) 
    return lesson_titles # Hoặc return lessons tùy vào logic của bạn

def get_theory(grade, title):
    return theory_data.get(grade, {}).get(title, "Nội dung đang được cập nhật...")